# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  resume:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/mohuk

    steps:
      - checkout

      - run:
          working_directory: resume
          command: yarn install

      - run:
          working_directory: resume
          command: npm run build
      - run:
          working_directory: resume
          command: firebase deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  resume-deploy:
    jobs:
      - resume
